---
blank_issues_enabled: false
contact_links:
  - about: Issues with detox -- E2E tests and automation for mobile
    name: 📦 detox
    url: https://github.com/wix/Detox/issues
  - about: Issues with ffmpeg-kit-react-native -- FFmpeg Kit for React Native
    name: 📦 ffmpeg-kit-react-native
    url: https://github.com/tanersener/ffmpeg-kit/issues
  - about: >-
      Issues with react-native-ble-plx -- React Native Bluetooth Low Energy
      library
    name: 📦 react-native-ble-plx
    url: https://github.com/Polidea/react-native-ble-plx/issues
  - about: >-
      Issues with react-native-blob-util -- A module provides upload, download,
      and files access API. Supports file stream read/write for process large
      files.
    name: 📦 react-native-blob-util
    url: https://github.com/RonRadtke/react-native-blob-util/issues
  - about: >-
      Issues with react-native-callkeep -- iOS 10 CallKit and Android
      ConnectionService Framework For React Native
    name: 📦 react-native-callkeep
    url: https://github.com/react-native-webrtc/react-native-callkeep/issues
  - about: >-
      Issues with react-native-dynamic-app-icon -- Programmatically change the
      app icon in React Native.
    name: 📦 react-native-dynamic-app-icon
    url: https://github.com/idearockers/react-native-dynamic-app-icon/issues
  - about: >-
      Issues with react-native-google-cast -- React Native wrapper for the
      Google Cast SDK for iOS and Android
    name: 📦 react-native-google-cast
    url: >-
      https://github.com/react-native-google-cast/react-native-google-cast/issues
  - about: >-
      Issues with react-native-pdf -- A react native PDF view component, support
      ios and android platform
    name: 📦 react-native-pdf
    url: https://github.com/wonday/react-native-pdf/issues
  - about: >-
      Issues with react-native-quick-actions -- A react-native interface for
      Touch 3D home screen quick actions
    name: 📦 react-native-quick-actions
    url: https://github.com/jordanbyron/react-native-quick-actions/issues
  - about: Issues with react-native-webrtc -- WebRTC for React Native
    name: 📦 react-native-webrtc
    url: https://github.com/react-native-webrtc/react-native-webrtc/issues
